apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-jhqw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-jhqw
    app.kubernetes.io/part-of: load-app-552f1484-2517-456d-8fe1-984a14abdfd3
  name: devfile-sample-python-basic-jhqw
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: devfile-sample-python-basic-jhqw
status:
  loadBalancer: {}
